### PR TITLE
fix build table

### LINKED ISSUE #2: 读取数据错误
作者你好，我用这个库和librime链接之后，参考tools/build_predict.cc中的main函数在Android写了一个录入数据的方法，代码如下：
``` C++
#include <rime/component.h>
#include <rime/registry.h>
#include <rime/service.h>
#include <rime_api.h>
#include <sstream>
#include <fstream>

#include "predictor.h"
#include "predict_db.h"

using namespace rime;

static bool file_exists(const char *fname) noexcept {
    FILE *const fp = fopen(fname, "r");
    if (fp) {
        fclose(fp);
        return true;
    }
    return false;
}

static void read(string file_name, rime::predict::RawData &data) {
    std::ifstream ifs1;
    ifs1.open(file_name);
    string str;
    while (getline(ifs1, str)) {
        std::istringstream ss(str);
        vector<string> words;
        string word;
        while (ss >> word) {
            words.push_back(word);
        }
        rime::predict::RawEntry entry;
        entry.text = words[1];
        entry.weight = std::stof(words[2]);
        data[words[0]].push_back(entry);
    }
    ifs1.close();
}

int init() {
    the<ResourceResolver> dres(Service::instance().CreateDeployedResourceResolver({"predict_db", "", ""}));
    string file_name_build = dres->ResolvePath("predict.db").string();
    if (file_exists(file_name_build.c_str())) {
        LOG(INFO) << "联想词目标文件已存在" << file_name_build;
        return 0;
    }
    the<ResourceResolver> res(Service::instance().CreateResourceResolver({"predict_db", "", ""}));
    string file_name = res->ResolvePath("sample.txt").string();
    if (!file_exists(file_name.c_str())) {
        LOG(ERROR) << "联想词源文件不存在" << file_name;
        return 0;
    }

    rime::predict::RawData data;
    LOG(INFO) << "联想词源文件 " << file_name;
    read(file_name, data);

    PredictDb db(file_name_build);
    LOG(INFO) << "creating " << db.file_name();
    if (!db.Build(data) || !db.Save()) {
        LOG(ERROR) << "failed to build " << db.file_name();
        return 1;
    }
    LOG(INFO) << "created: " << db.file_name();
    return 0;
}

static void rime_predict_initialize() {
    Registry &r = Registry::instance();
    init();
    r.Register("predictor", new PredictorComponent);
}

static void rime_predict_finalize() {
}

RIME_REGISTER_MODULE(predict)
```

但是在读取数据时候提示错误
image

希望指点

### LINKED ISSUE #4: 构建预测数据文件时报错
使用提供的样例数据文件sample.txt构建预测数据文件时报错，如下所示：

$ cat sample.txt | ./build_predict pre.db
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0605 21:16:26.009402 3191198 build_predict.cc:25] creating pre.db
I0605 21:16:26.009490 3191198 mapped_file.cc:89] overwriting file 'pre.db'.
I0605 21:16:26.009506 3191198 mapped_file.cc:163] resize file to: 2034
I0605 21:16:26.009568 3191198 mapped_file.cc:104] opening file for read/write access.
I0605 21:16:26.009732 3191198 mapped_file.cc:163] resize file to: 5576
Segmentation fault (core dumped)

使用较大的数据文件，似乎又没有问题。可以构建成功，代码显示可能在设置生成文件头信息时发生内存读写错误，看看怎么解决？

### PR DESCRIPTION
**Pull request by eagleoflqj**
Closes #2 
Closes #4

### CODE REVIEW

File: src/predict_db.cc [hunk 1]
```diff
@@ -67,13 +67,12 @@ bool PredictDb::Save() {
 }
 
 int PredictDb::WriteCandidates(const vector<predict::RawEntry>& candidates,
-                               StringTableBuilder* string_table) {
+                               StringTableBuilder* string_table,
+                               table::Entry*& entry) {
```
Comment (lotem) [inline src/predict_db.cc]: The type`table::Entry*&` is weird. It's hard for my fogged brain.
Let's avoid mutating the argument inside the function; use `table::Entry*` instead.

File: src/predict_db.cc [hunk 2]
```diff
@@ -83,67 +82,91 @@ bool PredictDb::Build(const predict::RawData& data) {
...
+
+  // copy from entry vector to entry array
+  table::Entry* entry = &entries[0];
   for (const auto& kv : data) {
     if (kv.second.empty())
       continue;
-    keys.push_back(kv.first.c_str());
-    values.push_back(WriteCandidates(kv.second, &string_table));
-    entry_count += kv.second.size();
+    values.push_back(WriteCandidates(kv.second, &string_table, entry));
```
Comment (lotem) [inline src/predict_db.cc]: Side-effect is difficult to keep in mind. Let's make `entry` input-only, and update the `entry` pointer with another statement after it:

``` c++
entry += kv.second.size();
```

That way, the reader knows how the variable is updated without looking into the implementation of `WriteCandidates`.

File: src/predict_db.cc [hunk 3]
```diff
@@ -83,67 +82,91 @@ bool PredictDb::Build(const predict::RawData& data) {
...
-  // build trie
-  StringTableBuilder string_table;
-  int entry_count = 0;
-  vector<const char*> keys;
-  vector<int> values;
-  keys.reserve(data_size);
-  values.reserve(data_size);
+
+  // copy from entry vector to entry array
+  table::Entry* entry = &entries[0];
```
Comment (lotem) [inline src/predict_db.cc]: a better name for the pointer can be `available_entries`.

**Review by lotem — CHANGES_REQUESTED** [review]
Thanks. You saved the project from a huge failure.

File: src/predict_db.cc (hunk 3 above)
Comment (lotem) [reply src/predict_db.cc]: a pointer type is the same as an array.
in this particular case, it's not just pointing to one entry but the start address of an array of entries.
so we can use plural in the name.

**Review by lotem — APPROVED** [review]
LGTM
